from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 550)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.name_lbl = QtWidgets.QLabel(Dialog)
        self.name_lbl.setGeometry(QtCore.QRect(180, 150, 71, 31))
        self.name_lbl.setStyleSheet("")
        self.name_lbl.setObjectName("name_lbl")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(180, 180, 251, 22))
        self.name.setText("")
        self.name.setObjectName("name")
        self.id = QtWidgets.QLineEdit(Dialog)
        self.id.setGeometry(QtCore.QRect(40, 180, 131, 22))
        self.id.setObjectName("id")
        self.id_lbl = QtWidgets.QLabel(Dialog)
        self.id_lbl.setGeometry(QtCore.QRect(40, 160, 71, 16))
        self.id_lbl.setObjectName("id_lbl")
        self.submit = QtWidgets.QPushButton(Dialog)
        self.submit.setGeometry(QtCore.QRect(260, 430, 93, 28))
        self.submit.setStyleSheet("background-color: rgb(183, 255, 156)")
        self.submit.setObjectName("submit")
        self.age = QtWidgets.QLineEdit(Dialog)
        self.age.setGeometry(QtCore.QRect(440, 180, 113, 22))
        self.age.setObjectName("age")
        self.age_lbl = QtWidgets.QLabel(Dialog)
        self.age_lbl.setGeometry(QtCore.QRect(440, 160, 71, 16))
        self.age_lbl.setObjectName("age_lbl")
        self.location = QtWidgets.QLineEdit(Dialog)
        self.location.setGeometry(QtCore.QRect(180, 230, 371, 22))
        self.location.setObjectName("location")
        self.location_lbl = QtWidgets.QLabel(Dialog)
        self.location_lbl.setGeometry(QtCore.QRect(180, 210, 55, 16))
        self.location_lbl.setObjectName("location_lbl")
        self.college = QtWidgets.QLineEdit(Dialog)
        self.college.setGeometry(QtCore.QRect(40, 230, 131, 22))
        self.college.setObjectName("college")
        self.college_lbl = QtWidgets.QLabel(Dialog)
        self.college_lbl.setGeometry(QtCore.QRect(40, 210, 55, 16))
        self.college_lbl.setObjectName("college_lbl")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 10, 111, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 270, 121, 16))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Dialog, clicked = lambda: self.select())
        self.radioButton.setGeometry(QtCore.QRect(40, 290, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog, clicked = lambda: self.select())
        self.radioButton_2.setGeometry(QtCore.QRect(40, 310, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 270, 281, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 290, 73, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 330, 141, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 350, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_lbl.setText(_translate("Dialog", "Name"))
        self.id_lbl.setText(_translate("Dialog", "Student ID"))
        self.submit.setText(_translate("Dialog", "Submit"))
        self.age_lbl.setText(_translate("Dialog", "Age"))
        self.location_lbl.setText(_translate("Dialog", "Location"))
        self.college_lbl.setText(_translate("Dialog", "College"))
        self.label_2.setText(_translate("Dialog", "Are you vaccinated?"))
        self.radioButton.setText(_translate("Dialog", "Yes"))
        self.radioButton_2.setText(_translate("Dialog", "No"))
        self.label_3.setText(_translate("Dialog", "If Yes, how many vaccine shots have you taken?"))
        self.comboBox.setItemText(0, _translate("Dialog", "None"))
        self.comboBox.setItemText(1, _translate("Dialog", "1"))
        self.comboBox.setItemText(2, _translate("Dialog", "2"))
        self.comboBox.setItemText(3, _translate("Dialog", "3 up"))
        self.label_4.setText(_translate("Dialog", "Name of Vaccine taken?"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Astrazeneca"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Moderna"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Johnson and Johnson\'s"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Pfizer"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "Covaxin"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "Sinopharm"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "Coronavac"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "Covishield"))

    def select(self):
        if self.radioButton.isChecked():
            self.vaccine_status = "Yes"
        elif self.radioButton.isChecked():
            self.vaccine_status = "No"


import sys
app = QtWidgets.QApplication(sys.argv)
Dialog = QtWidgets.QDialog()
ui = Ui_Dialog()
ui.setupUi(Dialog)
Dialog.show()
sys.exit(app.exec_())